title: Federal Data Strategy

# GitHub information
# This is used for adding an edit this page link to the footer

#Github Repo
repo_name: data-strategy
branch: master
org_name: GSA

# Configuration for Google Analytics, add your UA code here:
google_analytics_ua: UA-42145528-6

# Configuration for DAP, add your agency ID here:
dap_agency: GSA
