title: Federal Data Strategy

#Github Repo
repo_name: data-strategy
branch: gh-pages
org_name: GSA

# Configuration for Google Analytics, add your UA code here:
# google_analytics_ua: UA-XXXXXXXX-XX

# Configuration for DAP, add your agency ID here:
# dap_agency: GSA